export const testimonials = [
    {
      content: "This is an amazing product! Highly recommended.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSntKAFT9vdRUHpktbJPSuOBo3lDx_jGLAXXA&s",
      name: "John Doe",
      title: "CEO at Company",
      rating: 4.5,
    },
    {
      content: "Great service and support. Really happy with the results.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtVrvboc9jQvu7acrNZkgEM8GeHnsWIPVVVdK_GVRKIMzFd6ob86QvBgJQDcI0RK8xsN8&usqp=CAU",
      name: "Jane Smith",
      title: "Marketing Head",
      rating: 5,
    },
    {
      content: "The experience was fantastic. I would definitely come back.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ7Xf71WX1lGrli9YcmYNg3v91fnFFtrP36w&s",
      name: "Sam Wilson",
      title: "Project Manager",
      rating: 4,
    },
    {
      content: "Excellent customer support and great results.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW1yhlTpkCnujnhzP-xioiy9RdDQkKLMnMSg&s",
      name: "Linda Brown",
      title: "CTO at Another Company",
      rating: 4.5,
    },
    {
      content: "Very satisfied with the product and service.",
      avatar: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
      name: "Smart watch",
      title: "Freelancer",
      rating: 5,
    },
    {
      content: "A wonderful experience from start to finish.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4CDwV8uNnrqt0GGf-AWJbv2sxjG4iQ8jnR2Fpt7waKG62f4hRauQ4kFeIVEf5oC3juFo&usqp=CAU",
      name: "Emily Davis",
      title: "Designer",
      rating: 4,
    }, {
      content: "This is an amazing product! Highly recommended.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSntKAFT9vdRUHpktbJPSuOBo3lDx_jGLAXXA&s",
      name: "John Doe",
      title: "CEO at Company",
      rating: 4.5,
    },
    {
      content: "Great service and support. Really happy with the results.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtVrvboc9jQvu7acrNZkgEM8GeHnsWIPVVVdK_GVRKIMzFd6ob86QvBgJQDcI0RK8xsN8&usqp=CAU",
      name: "Jane Smith",
      title: "Marketing Head",
      rating: 5,
    },
    {
      content: "Very satisfied with the product and service.",
      avatar: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
      name: "Smart watch",
      title: "Freelancer",
      rating: 5,
    },
    {
      content: "A wonderful experience from start to finish.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4CDwV8uNnrqt0GGf-AWJbv2sxjG4iQ8jnR2Fpt7waKG62f4hRauQ4kFeIVEf5oC3juFo&usqp=CAU",
      name: "Emily Davis",
      title: "Designer",
      rating: 4,
    }, {
      content: "This is an amazing product! Highly recommended.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSntKAFT9vdRUHpktbJPSuOBo3lDx_jGLAXXA&s",
      name: "John Doe",
      title: "CEO at Company",
      rating: 4.5,
    },
    {
      content: "Great service and support. Really happy with the results.",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtVrvboc9jQvu7acrNZkgEM8GeHnsWIPVVVdK_GVRKIMzFd6ob86QvBgJQDcI0RK8xsN8&usqp=CAU",
      name: "Jane Smith",
      title: "Marketing Head",
      rating: 5,
    },
  ];
  export const ThirdCardData = [
    {
      content: "This is an amazing product! Highly recommended.",
      avatar: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?cs=srgb&dl=pexels-joey-nguy-n-1056657-2113994.jpg&fm=jpg",
      name: "John Doe",
      title: "CEO at Company",
      rating: 4.5,
    },
    {
      content: "Great service and support. Really happy with the results.",
      avatar: "https://helloaugust.in/wp-content/uploads/2022/06/hero-330-fountain-pen.jpg",
      name: "Jane Smith",
      title: "Marketing Head",
      rating: 5,
    },
    {
      content: "The experience was fantastic. I would definitely come back.",
      avatar: "https://rukminim2.flixcart.com/image/850/1000/xif0q/cycle/n/x/l/old-skool-26t-cycle-26-23-east-coast-115-single-speed-original-imagmzejgzzyd2ga.jpeg?q=90&crop=false",
      name: "Sam Wilson",
      title: "Project Manager",
      rating: 4,
    },
    {
      content: "Excellent customer support and great results.",
      avatar: "https://5.imimg.com/data5/SELLER/Default/2023/6/315272898/PY/ZX/QI/67393073/kids-toys-500x500.webp",
      name: "Linda Brown",
      title: "CTO at Another Company",
      rating: 4.5,
    },
    {
      content: "Very satisfied with the product and service.",
      avatar: "https://5.imimg.com/data5/CL/BG/MY-3653823/se-219bt-1-500x500.jpg",
      name: "Smart watch",
      title: "Freelancer",
      rating: 5,
    }]
  export const fourthCardData = [
    {
      content: "This is an amazing product! Highly recommended.",
      avatar: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?cs=srgb&dl=pexels-joey-nguy-n-1056657-2113994.jpg&fm=jpg",
      name: "John Doe",
      title: "CEO at Company",
      rating: 4.5,
    },
    {
      content: "Great service and support. Really happy with the results.",
      avatar: "https://helloaugust.in/wp-content/uploads/2022/06/hero-330-fountain-pen.jpg",
      name: "Jane Smith",
      title: "Marketing Head",
      rating: 5,
    },
    {
      content: "The experience was fantastic. I would definitely come back.",
      avatar: "https://rukminim2.flixcart.com/image/850/1000/xif0q/cycle/n/x/l/old-skool-26t-cycle-26-23-east-coast-115-single-speed-original-imagmzejgzzyd2ga.jpeg?q=90&crop=false",
      name: "Sam Wilson",
      title: "Project Manager",
      rating: 4,
    },
    {
      content: "Excellent customer support and great results.",
      avatar: "https://5.imimg.com/data5/SELLER/Default/2023/6/315272898/PY/ZX/QI/67393073/kids-toys-500x500.webp",
      name: "Linda Brown",
      title: "CTO at Another Company",
      rating: 4.5,
    },
    {
      content: "Very satisfied with the product and service.",
      avatar: "https://5.imimg.com/data5/CL/BG/MY-3653823/se-219bt-1-500x500.jpg",
      name: "Smart watch",
      title: "Freelancer",
      rating: 5,
    },
    {
      content: "Great service and support. Really happy with the results.",
      avatar: "https://helloaugust.in/wp-content/uploads/2022/06/hero-330-fountain-pen.jpg",
      name: "Jane Smith",
      title: "Marketing Head",
      rating: 5,
    },
    {
      content: "The experience was fantastic. I would definitely come back.",
      avatar: "https://rukminim2.flixcart.com/image/850/1000/xif0q/cycle/n/x/l/old-skool-26t-cycle-26-23-east-coast-115-single-speed-original-imagmzejgzzyd2ga.jpeg?q=90&crop=false",
      name: "Sam Wilson",
      title: "Project Manager",
      rating: 4,
    }
    ,
    {
      content: "Very satisfied with the product and service.",
      avatar: "https://5.imimg.com/data5/CL/BG/MY-3653823/se-219bt-1-500x500.jpg",
      name: "Smart watch",
      title: "Freelancer",
      rating: 5,
    },
    {
      content: "Great service and support. Really happy with the results.",
      avatar: "https://helloaugust.in/wp-content/uploads/2022/06/hero-330-fountain-pen.jpg",
      name: "Jane Smith",
      title: "Marketing Head",
      rating: 5,
    },
    {
      content: "The experience was fantastic. I would definitely come back.",
      avatar: "https://rukminim2.flixcart.com/image/850/1000/xif0q/cycle/n/x/l/old-skool-26t-cycle-26-23-east-coast-115-single-speed-original-imagmzejgzzyd2ga.jpeg?q=90&crop=false",
      name: "Sam Wilson",
      title: "Project Manager",
      rating: 4,
    }]